export { default as Hero } from './hero'
export { default as About } from './about'
export { default as Requests } from './requests'
export { default as Info } from './info'
export { default as Security } from './security'
export { default as Data } from './data'
export { default as Features } from './features'
